version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/frontend

    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build

      - save_cache:
          paths:
            - node_modules
          key: projectname-{{ .Branch }}-{{ checksum "package.json" }}
